apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuard
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    kind: ReplicaSet
    name: kuard
  targetCPUUtilizationPercentage: 50