apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      nfs:
        path: "/mnt/nfsdata/kudard/data"
        server: "172.31.240.127"
  containers:
    - image: registry.cn-shenzhen.aliyuncs.com/cookcodeblog/kuard-amd64:1
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
